### PR TITLE
datebook_gui.c warning removals

### PR DESCRIPTION
**Pull request by dmalia1**
It looks like you had it almost figured out.
I replaced all instances of GDK_TYPE_COLOR with GDK_TYPE_RGBA.
I think the warning for datebook_gui.c is now gone.

### CODE REVIEW

**Comment by juddmon** [comment]
I did try that.  Did  you see it causes a lot of these messages?
`(jpilot:3030549): GLib-GObject-WARNING **: 20:07:37.715: unable to set property 'cell-background-gdk' of type 'GdkColor' from value of type 'GdkRGBA'`

**Comment by dmalia1** [comment]
no.. I just noticed the colors are gone too.  I was too focused on getting rid of the warning.

**Comment by dmalia1** [comment]
switching to gdkRGBA seems to fix it..  I'm not sure if I got the int hex values quite right though.

**Comment by dmalia1** [comment]
I think its ok now.

**Pull request merged**
