### PR TITLE
Gtk3build

### PR DESCRIPTION
**Pull request by dmalia1**
My changes so far for getting this to build with GTK3.
I stabilized the main four apps so it doesn't crash as often.

Some known issues:
1. Setting the colors for the themes isn't working on GTK3
2. If you jump from Todos to datebook, to address, to datebook, then back to todos, the categories are missing
3. Some of the buttons seem a bit out of alignment, as well as some of the text.

There is probably other issues with this as well.  I wouldn't necessarily call this production ready at this point,
but this is getting all the changes so far into Judd's repo, on a branch to not interfere with master.

Note:  You can swap out the configure.in for the gtk2 build, and it should still work.  Some of the issues that are present with the GTK3 build go away with the GTK2 build.  Some of the issues are there either way.

### CODE REVIEW

**Comment by eklausme** [comment]
Looks very good.

Compiled the same, but had to change configure.in to allow for pilot-link
0.12.5, instead of 0.13.0.

I was totally excited to see J-Pilot running under broadwayd in my browser!

Thanks a lot.

**Comment by dmalia1** [comment]
0.13.0 of pilot-link is on master of https://github.com/desrod/pilot-link/.
Its needed to eliminate the python 2 dependency which was one of the reasons why this got pulled out of ubuntu's repos.

**Comment by dmalia1** [comment]
I fixed the issue with the left-hand category menus randomly disappearing.
I also fixed the issue with the preferences not showing the selected theme.

Speaking of themes.  I don't think this is loading the theme, which is why it looks a little off.  I believe its because Gtk 3 has deperecated the gtkStyle that it was using with GTK 3.0, and needs to be replaced.  the rc files might need to be updated to css files.  I'll spend some time looking at that when I can.

The app should be stable.  There may be some issues with loading/saving/creating  files to the local filesystem on exports/imports.  I'm not sure I used the appropriate methods.  I'll need to look at that as well.

**Comment by eklausme** [comment]
I played around with the latest commit-version 73a472470:

1. Entering a new date does not allow to enter start or end time by keying, i.e., by using the keyboard. For example, entering a date at 17:20. Numeric characters seems to get subtracted by some random number.

2. Searching for items: Items are found, but do not select the items on the right side, i.e., for dates it only shows the matching part on the left pane of the date screen; same for memos: correct memo is found and display on left pane, but corresponding right pane is not shown

In case required, I can provide screenshots and will link them here.

**Comment by dmalia1** [comment]
screenshots would be helpful.  There are several places where dates are entered.  I did notice some weirdness with the dates that I had thought I had fixed, but its probable I missed something.  Its verify likely events aren't triggering everything the same as the GtkClist object had different events that the GTKTreeView does on the searching. I can look into it.

**Comment by dmalia1** [comment]
hmm.. I just noticed this pull request goes to master.  I meant for it to go to the gtk3 branch.  Since eklauseme is adding some helpful qa comments, I'll leave it open for now, and create another one to push to the gtk3 branch.

**Comment by dmalia1** [comment]
@eklausme 
I started looking at number one.  It looks like a pre-existing issue if I understand the problem correctly.   I'm assuming you are talking about where you can type in an input to set the times when picking a time to set the appointment.  The times are in 12 hour format.  When you type, its trying to autoselect the time from the dropdown.  I'm not sure if it was meant to be typed in.  I can maybe not make those text entries editable.

I'm starting to look at number 2, as I can see its not populating the right side of the pane correctly.

**Comment by dmalia1** [comment]
Ok.. The find functionality should be working ok now and properly loading the right-hand side pane.

**Pull request closed without merging**
